/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.sysbliss.jira.plugins.workflow.exception {

    [Bindable]
    [RemoteClass(alias="com.sysbliss.jira.plugins.workflow.exception.FlexNotLoggedInException")]
    public class FlexNotLoggedInException extends FlexNotLoggedInExceptionBase {

        public function FlexNotLoggedInException(message:String="", id:int=0){
			super(message, id);
		}
    }
}