Return-Path: <bbain@localhost>
Delivered-To: bbain@localhost
Received: from localhost ([127.0.0.1])
          by honey2.sydney.atlassian.com (JAMES SMTP Server 2.3.1) with SMTP ID 942
          for <bbain@localhost>;
          Fri, 16 Jan 2009 11:40:08 +1100 (EST)
Message-Id: <E3C57B1A-7777-4C25-8D07-3FE2C2C5F043@localhost>
From: Brenden Bain <bbain@localhost>
To: b bain@localhost
Content-Type: text/plain; charset=US-ASCII; format=flowed
Content-Transfer-Encoding: 7bit
Mime-Version: 1.0 (Apple Message framework v930.3)
Subject: This message has a very bad e-mail address.
Date: Fri, 16 Jan 2009 11:40:08 +1100
X-Mailer: Apple Mail (2.930.3)

This message contains an e-mail that JavaMail cannot handle.

Later,
Brenden.
