Return-Path: jira-test@atlassian.com
Received: from mail.atlassian.com (LHLO mail.atlassian.com) (63.246.22.40)
 by mail.atlassian.com with LMTP; Tue, 29 Jul 2008 23:14:32 -0500 (CDT)
Received: from [192.168.168.129] (unknown [203.63.130.33])
	by mail.atlassian.com (Postfix) with ESMTP id BCD0E378C17
	for <mpokorny@atlassian.com>; Tue, 29 Jul 2008 23:14:31 -0500 (CDT)
Subject: EvolutionPlainText
From: JIRA Test <jira-test@atlassian.com>
To: mpokorny@atlassian.com
Content-Type: text/plain
Date: Fri, 13 Jun 2008 22:32:25 +1000
Message-Id: <1213360345.16444.4.camel@atlassian-desktop>
Mime-Version: 1.0
X-Mailer: Evolution 2.6.1 
Content-Transfer-Encoding: 7bit

This is a plain text email

