Return-Path: jirauser@atlassian.com
Received: from mail.atlassian.com (LHLO mail.atlassian.com) (63.246.22.40)
 by mail.atlassian.com with LMTP; Thu, 10 Jul 2008 21:44:30 -0500 (CDT)
Received: from [192.168.0.172] (unknown [203.63.130.33])
	by mail.atlassian.com (Postfix) with ESMTP id A2BE816324F2
	for <jirauser@atlassian.com>; Thu, 10 Jul 2008 21:44:29 -0500 (CDT)
Subject: Evolution Html
From: JIRA TEST USER <jirauser@atlassian.com>
To: JIRA TEST USER <jirauser@atlassian.com>
Content-Type: multipart/alternative; boundary="=-xpzn65DDrsYNe7YKcOXf"
Date: Fri, 11 Jul 2008 12:44:14 +1000
Message-Id: <1215744254.4507.72.camel@carltondraught>
Mime-Version: 1.0
X-Mailer: Evolution 2.22.2 


--=-xpzn65DDrsYNe7YKcOXf
Content-Type: text/plain;
Content-Transfer-Encoding: 8bit

BOLD underlineditalics


--=-xpzn65DDrsYNe7YKcOXf
Content-Type: text/html;
Content-Transfer-Encoding: 7bit

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 TRANSITIONAL//EN">
<HTML>
<HEAD>
  <META HTTP-EQUIV="Content-Type" CONTENT="text/html;">
  <META NAME="GENERATOR" CONTENT="GtkHTML/3.18.2">
</HEAD>
<BODY>
<B>BOLD</B> <U>underlined</U><I>italics</I><BR>
<TABLE CELLSPACING="0" CELLPADDING="0" WIDTH="100%">
<TR>
<TD>
<BR>
</TD>
</TR>
</TABLE>
</BODY>
</HTML>

--=-xpzn65DDrsYNe7YKcOXf--

