Return-Path: jira-test@atlassian.com
Received: from mail.atlassian.com (LHLO mail.atlassian.com) (63.246.22.40)
 by mail.atlassian.com with LMTP; Tue, 29 Jul 2008 23:20:04 -0500 (CDT)
Received: from [192.168.168.129] (unknown [203.63.130.33])
	by mail.atlassian.com (Postfix) with ESMTP id 3B6AE378C5E
	for <mpokorny@atlassian.com>; Tue, 29 Jul 2008 23:20:03 -0500 (CDT)
Subject: EvolutionPlainTextWithHtmlAttachment
From: JIRA Test <jira-test@atlassian.com>
To: mpokorny@atlassian.com
Content-Type: multipart/mixed; boundary="=-IoOwqPxJREFpIDchKt3B"
Date: Fri, 13 Jun 2008 22:37:57 +1000
Message-Id: <1213360677.16444.8.camel@atlassian-desktop>
Mime-Version: 1.0
X-Mailer: Evolution 2.6.1 


--=-IoOwqPxJREFpIDchKt3B
Content-Type: text/plain
Content-Transfer-Encoding: 7bit

Plain text.
There should be an HTML attachment here.

--=-IoOwqPxJREFpIDchKt3B
Content-Disposition: attachment; filename=page.html
Content-Type: text/html; name=page.html; charset=UTF-8
Content-Transfer-Encoding: 7bit

<html>
<body>
<b>BOLD</b>
<i>italics</i>
Plain text
</body>
</html>

--=-IoOwqPxJREFpIDchKt3B--

