Return-Path: jira-test@atlassian.com
Received: from mail.atlassian.com (LHLO mail.atlassian.com) (63.246.22.40)
 by mail.atlassian.com with LMTP; Wed, 30 Jul 2008 00:07:57 -0500 (CDT)
Received: from [192.168.168.129] (unknown [203.63.130.33])
	by mail.atlassian.com (Postfix) with ESMTP id 8B679378E30
	for <mpokorny@atlassian.com>; Wed, 30 Jul 2008 00:07:56 -0500 (CDT)
Subject: EvolutionHtmlWithPlainTextAttachment
From: JIRA Test <jira-test@atlassian.com>
To: mpokorny@atlassian.com
Content-Type: multipart/mixed; boundary="=-d04g3W0kVzgqxk6kni0u"
Date: Fri, 13 Jun 2008 23:25:50 +1000
Message-Id: <1213363550.16444.21.camel@atlassian-desktop>
Mime-Version: 1.0
X-Mailer: Evolution 2.6.1 


--=-d04g3W0kVzgqxk6kni0u
Content-Type: multipart/alternative; boundary="=-vxyivpOFYgvlP8hpjIM6"


--=-vxyivpOFYgvlP8hpjIM6
Content-Type: text/plain
Content-Transfer-Encoding: 7bit

This is an HTML email:

BOLD
italics!
plain text

Plain text attachment to follow.

--=-vxyivpOFYgvlP8hpjIM6
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 7bit

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 TRANSITIONAL//EN">
<HTML>
<HEAD>
  <META HTTP-EQUIV="Content-Type" CONTENT="text/html; CHARSET=UTF-8">
  <META NAME="GENERATOR" CONTENT="GtkHTML/3.10.3">
</HEAD>
<BODY>
This is an HTML email:<BR>
<BR>
<B>BOLD</B><BR>
<I>italics!</I><BR>
plain text<BR>
<BR>
Plain text attachment to follow.
</BODY>
</HTML>

--=-vxyivpOFYgvlP8hpjIM6--

--=-d04g3W0kVzgqxk6kni0u
Content-Disposition: attachment; filename=plain.txt
Content-Type: text/plain; name=plain.txt; charset=UTF-8
Content-Transfer-Encoding: 7bit

This is a plain text file!

--=-d04g3W0kVzgqxk6kni0u--

