Return-Path: miroslav.pokorny@gmail.com
Received: from mail.atlassian.com (LHLO mail.atlassian.com) (63.246.22.40)
 by mail.atlassian.com with LMTP; Wed, 23 Jul 2008 01:05:54 -0500 (CDT)
Received: from p02c11m092.mxlogic.net (mxl144v245.mxlogic.net [208.65.144.245])
	by mail.atlassian.com (Postfix) with ESMTP id B1B603EB045
	for <mpokorny@atlassian.com>; Wed, 23 Jul 2008 01:05:52 -0500 (CDT)
Received: from unknown [209.85.142.187] (EHLO ti-out-0910.google.com)
	by p02c11m092.mxlogic.net (mxl_mta-5.6.0-1)
	with ESMTP id 04ac6884.3453733808.4789.00-152.p02c11m092.mxlogic.net (envelope-from <miroslav.pokorny@gmail.com>);
	Wed, 23 Jul 2008 00:05:52 -0600 (MDT)
Received: by ti-out-0910.google.com with SMTP id w7so1165658tib.13
        for <mpokorny@atlassian.com>; Tue, 22 Jul 2008 23:05:51 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=gamma;
        h=domainkey-signature:received:received:message-id:date:from:to
         :subject:mime-version:content-type;
        bh=hF/YviWHqVJzygQngAxhU3UtxAqdKYtWbHtqNJ5aT4c=;
        b=u5UxOvQG6GWBNa9Aw2iXOpm6XTHARle9/SPf87APPOun4AumhUVpjKpZEwKKdKhkdJ
         QBnXA8VYY7+RK8QD4E+7G5nsEm9AmPAfjaPn3m9V1PxItEb6fQEG32NYx3kV9aobbCe7
         AsbPaa2L4osjhVP2suRM4BNtA0AZxkLdZSsmg=
DomainKey-Signature: a=rsa-sha1; c=nofws;
        d=gmail.com; s=gamma;
        h=message-id:date:from:to:subject:mime-version:content-type;
        b=f6kgu956IOwYxKWrGdERnunoNOz4NuRzNufldQjiAH9/G/w8BRIWIsTJtHVFeB8WWa
         BWE5dA1pJWMWFGxXRwYEbEnhSYC1IXvxqMppZydCLZB/o7a1KGNjlcAsBgB426Objf++
         BCqc9sEBQWH9NLZ1BkFLwK8/sebJVH+pEH0Gg=
Received: by 10.110.95.15 with SMTP id s15mr5421815tib.40.1216793150311;
        Tue, 22 Jul 2008 23:05:50 -0700 (PDT)
Received: by 10.110.39.16 with HTTP; Tue, 22 Jul 2008 23:05:50 -0700 (PDT)
Message-ID: <3ba4a7240807222305l3a55b9c6ib7b81303f99682@mail.gmail.com>
Date: Wed, 23 Jul 2008 16:05:50 +1000
From: "Miroslav Pokorny" <miroslav.pokorny@gmail.com>
To: mpokorny@atlassian.com
Subject: GMailHtmlWithHtmlAttachment
MIME-Version: 1.0
Content-Type: multipart/mixed; 
	boundary="----=_Part_141854_1005635.1216793150296"
X-Spam: [F=0.0135709030; B=0.500(0); spf=0.500; CM=0.500; MH=0.500(2008072232); R=0.110(108622192526); S=0.100(2008062001); SS=0.500; SC=none]
X-MAIL-FROM: <miroslav.pokorny@gmail.com>
X-SOURCE-IP: [209.85.142.187]
X-AnalysisOut: [v=1.0 c=1 a=WgbEJvYFGFO8GTGX2wYA:9 a=rwm-qREH6OCFvmMtsYMpX]
X-AnalysisOut: [W2LxlMA:4 a=thrRgKss0rMA:10 a=wZZYKQAxMQF7EjFMdAsA:9 a=geD]
X-AnalysisOut: [RTkOaI9cIslEy0Aku4mi6LSoA:4 a=qJMeZhlYfXQA:10 a=5gicP0EE_V]
X-AnalysisOut: [c982eSOYoA:9 a=ABRf56cPosR6w0lO1ghRP2hClqgA:4 a=37WNUvjkh6]
X-AnalysisOut: [kA:10]

------=_Part_141854_1005635.1216793150296
Content-Type: multipart/alternative; 
	boundary="----=_Part_141855_25119965.1216793150296"

------=_Part_141855_25119965.1216793150296
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: 7bit
Content-Disposition: inline

BOLD

The html page attachment should be kept...

-- 
mP

------=_Part_141855_25119965.1216793150296
Content-Type: text/html; charset=ISO-8859-1
Content-Transfer-Encoding: 7bit
Content-Disposition: inline

<div dir="ltr">BOLD<br><br>The html page attachment should be kept...<br clear="all"><br>-- <br>mP
</div>

------=_Part_141855_25119965.1216793150296--

------=_Part_141854_1005635.1216793150296
Content-Type: text/html; name=page.html
Content-Transfer-Encoding: base64
X-Attachment-Id: f_fizj7e4i0
Content-Disposition: attachment; filename=page.html

PGh0bWw+DQo8aGVhZCAvPg0KPGJvZHk+DQpBIHZlcnkgc2ltcGxlIGh0bWwgZmlsZS4uLg0KPC9i
b2R5Pg0KPC9odG1sPg==
------=_Part_141854_1005635.1216793150296--
