Return-Path: jirauser@gmail.com
Received: from mail.atlassian.com (LHLO mail.atlassian.com) (63.246.22.40)
 by mail.atlassian.com with LMTP; Thu, 10 Jul 2008 21:14:57 -0500 (CDT)
Received: from p02c11m022.mxlogic.net (mxl144v245.mxlogic.net [208.65.144.245])
	by mail.atlassian.com (Postfix) with ESMTP id 89F6316324F2
	for <jirauser@atlassian.com>; Thu, 10 Jul 2008 21:14:57 -0500 (CDT)
Received: from unknown [209.85.142.187] (EHLO ti-out-0910.google.com)
	by p02c11m022.mxlogic.net (mxl_mta-5.6.0-1)
	with ESMTP id 122c6784.3664202672.14124.00-006.p02c11m022.mxlogic.net (envelope-from <jirauser@gmail.com>);
	Thu, 10 Jul 2008 20:14:57 -0600 (MDT)
Received: by ti-out-0910.google.com with SMTP id w7so1646956tib.13
        for <jirauser@atlassian.com>; Thu, 10 Jul 2008 19:14:56 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=gamma;
        h=domainkey-signature:received:received:message-id:date:from:to
         :subject:mime-version:content-type;
        bh=xBTUOi6oRWq0Ky8vDROovgyuyUOUBzyzu+2GNdEky+s=;
        b=Asvp7TOUZIf89av7MfWAD5UAKH6RnskXO7VAJVE1pOkcGGYBL0edn6ohYI3BEQHYxY
         qYadRNAz1EjNMq7qvH7j6r0BL4zDQP0Ybbv6UAkBE054zMR0pdFew3iGO+WdnlhUiHWd
         Ud7llo8J0Qn8zpLkEhPvrvylhR89KSnzWt1Ak=
DomainKey-Signature: a=rsa-sha1; c=nofws;
        d=gmail.com; s=gamma;
        h=message-id:date:from:to:subject:mime-version:content-type;
        b=w/riGX2tfUhX+VKRTGzZ/wTF5yJLh+JFdBwRcjCLf765u+iQMvwIBc9Lb2c2LVaco3
         dkZ2A7nUtwLpkFcS4D6QGNcZ66AF9Q0J7Agu2dhRtN9QfOFhvw0LX+7rfnICVyEE/HAQ
         rzaCRKJePqd6fR50xCVuqCJnxykK10Je7uZu8=
Received: by 10.110.20.17 with SMTP id 17mr5510222tit.12.1215742495580;
        Thu, 10 Jul 2008 19:14:55 -0700 (PDT)
Received: by 10.110.39.16 with HTTP; Thu, 10 Jul 2008 19:14:55 -0700 (PDT)
Message-ID: <3ba4a7240807101914u2e31a8c3q78498291fa38eade@mail.gmail.com>
Date: Fri, 11 Jul 2008 12:14:55 +1000
From: "JIRA TEST USER" <jirauser@gmail.com>
To: jirauser@atlassian.com
Subject: Gmail Html
MIME-Version: 1.0
Content-Type: multipart/alternative; 
	boundary="----=_Part_45629_22601741.1215742495580"
X-Spam: [F=0.0117722861; B=0.500(0); spf=0.500; CM=0.500; MH=0.500(2008071035); R=0.096(108610195532); S=0.100(2008062001); SS=0.500; SC=none]
X-MAIL-FROM: <jirauser@gmail.com>
X-SOURCE-IP: [209.85.142.187]
X-AnalysisOut: [v=1.0 c=1 a=VUvnqsgs1WA4keTt7pUA:9 a=DUxLZnoV5fxNfHSCVEg1Y]
X-AnalysisOut: [xsh2-QA:4 a=yGn54wW5l98A:10 a=MBJGtllbOqpbWLco1f0A:9 a=AFy]
X-AnalysisOut: [ZLZjba1kqlSYfTwIBZI2AFmwA:4 a=YGxRMErdduYA:10]

------=_Part_45629_22601741.1215742495580
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: 7bit
Content-Disposition: inline

*BOLD

**Italics**

**Underlined**
*

------=_Part_45629_22601741.1215742495580
Content-Type: text/html; charset=ISO-8859-1
Content-Transfer-Encoding: 7bit
Content-Disposition: inline

<b>BOLD<br><br></b><i>Italics</i><b><br><br></b><u>Underlined</u><b><br></b><br>-- <br>mP<br>

------=_Part_45629_22601741.1215742495580--
