Return-Path: mpokorny@atlassian.com
Received: from mail.atlassian.com (LHLO mail.atlassian.com) (63.246.22.40)
 by mail.atlassian.com with LMTP; Wed, 23 Jul 2008 20:52:50 -0500 (CDT)
Received: from xpie7 (unknown [203.63.130.33])
	by mail.atlassian.com (Postfix) with SMTP id 531E416324C7
	for <mpokorny@atlassian.com>; Wed, 23 Jul 2008 20:52:49 -0500 (CDT)
Message-ID: <003101c8ed30$c5986090$9803a8c0@xpie7>
From: "Miroslav Pokorny" <mpokorny@atlassian.com>
To: <mpokorny@atlassian.com>
Subject: OutlookHtmlWithPlainTextAttachment
Date: Thu, 24 Jul 2008 11:58:28 +1000
MIME-Version: 1.0
Content-Type: multipart/mixed;
	boundary="----=_NextPart_000_002D_01C8ED84.961F2A70"
X-Priority: 3
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 6.00.2900.3138
X-MimeOLE: Produced By Microsoft MimeOLE V6.00.2900.3198

This is a multi-part message in MIME format.

------=_NextPart_000_002D_01C8ED84.961F2A70
Content-Type: multipart/alternative;
	boundary="----=_NextPart_001_002E_01C8ED84.961F2A70"


------=_NextPart_001_002E_01C8ED84.961F2A70
Content-Type: text/plain;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

Bold

italics

plain.txt file is attached.
------=_NextPart_001_002E_01C8ED84.961F2A70
Content-Type: text/html;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD>
<META http-equiv=3DContent-Type content=3D"text/html; =
charset=3Diso-8859-1">
<META content=3D"MSHTML 6.00.6000.16587" name=3DGENERATOR>
<STYLE></STYLE>
</HEAD>
<BODY bgColor=3D#ffffff>
<DIV><FONT face=3DArial size=3D2><STRONG>Bold</STRONG></FONT></DIV>
<DIV><FONT face=3DArial size=3D2><EM></EM></FONT>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2><EM>italics</EM></FONT></DIV>
<DIV><EM><FONT face=3DArial size=3D2></FONT></EM>&nbsp;</DIV>
<DIV><FONT face=3DArial color=3D#800000 size=3D2>plain.txt file is=20
attached.</FONT></DIV></BODY></HTML>

------=_NextPart_001_002E_01C8ED84.961F2A70--

------=_NextPart_000_002D_01C8ED84.961F2A70
Content-Type: text/plain;
	name="plain.txt"
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment;
	filename="plain.txt"

Lorem ipsum
------=_NextPart_000_002D_01C8ED84.961F2A70--

