Return-Path: mpokorny@atlassian.com
Received: from mail.atlassian.com (LHLO mail.atlassian.com) (63.246.22.40)
 by mail.atlassian.com with LMTP; Wed, 23 Jul 2008 01:02:56 -0500 (CDT)
Received: from [192.168.3.151] (unknown [203.63.130.33])
	by mail.atlassian.com (Postfix) with ESMTP id A02253EAED2
	for <mpokorny@atlassian.com>; Wed, 23 Jul 2008 01:02:55 -0500 (CDT)
Message-ID: <4886C980.3020806@atlassian.com>
Date: Wed, 23 Jul 2008 16:02:40 +1000
From: Miroslav Pokorny <mpokorny@atlassian.com>
User-Agent: Thunderbird 2.0.0.14 (Windows/20080421)
MIME-Version: 1.0
To: mpokorny@atlassian.com
Subject: ThunderbirdHtmlWithHtmlAttachment
Content-Type: multipart/mixed;
 boundary="------------010302070004050606020308"

This is a multi-part message in MIME format.
--------------010302070004050606020308
Content-Type: multipart/alternative;
 boundary="------------020407060306050009080903"


--------------020407060306050009080903
Content-Type: text/plain; charset=ISO-8859-1; format=flowed
Content-Transfer-Encoding: 7bit

*BOLD*
/italics/

--------------020407060306050009080903
Content-Type: text/html; charset=ISO-8859-1
Content-Transfer-Encoding: 7bit

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
</head>
<body bgcolor="#ffffff" text="#000000">
<b>BOLD</b><br>
<i>italics</i><br>
</body>
</html>

--------------020407060306050009080903--

--------------010302070004050606020308
Content-Type: text/html;
 name="page.html"
Content-Transfer-Encoding: base64
Content-Disposition: inline;
 filename="page.html"

PGh0bWw+DQo8aGVhZCAvPg0KPGJvZHk+DQpBIHZlcnkgc2ltcGxlIGh0bWwgZmlsZS4uLg0K
PC9ib2R5Pg0KPC9odG1sPg==
--------------010302070004050606020308--
