Return-Path: jiratest@atlassian.com
Received: from mail.atlassian.com (LHLO mail.atlassian.com) (63.246.22.40)
 by mail.atlassian.com with LMTP; Wed, 9 Jul 2008 01:58:18 -0500 (CDT)
Received: from [192.168.3.151] (unknown [203.63.130.33])
	by mail.atlassian.com (Postfix) with ESMTP id A885A16324F2
	for <jiratest@atlassian.com>; Wed,  9 Jul 2008 01:58:17 -0500 (CDT)
Message-ID: <48746181.4070807@atlassian.com>
Date: Wed, 09 Jul 2008 16:58:09 +1000
From: jiratest <jiratest@atlassian.com>
User-Agent: Thunderbird 2.0.0.14 (Windows/20080421)
MIME-Version: 1.0
To: jiratest@atlassian.com
Subject: Thunderbird PlainText ImageAttachment
Content-Type: text/plain; charset=ISO-8859-1; format=flowed
Content-Transfer-Encoding: 7bit

   
*orter:* 	Maxim Dyuzhinov 
<http://jira.atlassian.com/secure/ViewProfile.jspa?name=maximd>
*Votes:* 	1
*Watchers:* 	5

*Operations*


If you were logged in 
<http://jira.atlassian.com/secure/Dashboard.jspa?os_destination=%2Fbrowse%2FJRA-13720> 
you would be able to see more operations.
The attached image should be lost.
