Return-Path: jirauser@atlassian.com
Received: from mail.atlassian.com (LHLO mail.atlassian.com) (63.246.22.40)
 by mail.atlassian.com with LMTP; Thu, 10 Jul 2008 20:51:26 -0500 (CDT)
Received: from xpie7 (unknown [203.63.130.33])
	by mail.atlassian.com (Postfix) with ESMTP id ED68016324F2
	for <jirauser@atlassian.com>; Thu, 10 Jul 2008 20:51:25 -0500 (CDT)
Message-ID: <002501c8e2f9$5dda2290$9803a8c0@xpie7>
From: "jirauser" <jirauser@atlassian.com>
To: <jirauser@atlassian.com>
Subject: Outlook PlainText
Date: Fri, 11 Jul 2008 11:56:40 +1000
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="----=_NextPart_000_0022_01C8E34D.2DE023B0"
X-Priority: 3
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 6.00.2900.3138
X-MimeOLE: Produced By Microsoft MimeOLE V6.00.2900.3198

This is a multi-part message in MIME format.

------=_NextPart_000_0022_01C8E34D.2DE023B0
Content-Type: text/plain;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

Plain Text - no html markup.
------=_NextPart_000_0022_01C8E34D.2DE023B0
Content-Type: text/html;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD>
<META http-equiv=3DContent-Type content=3D"text/html; =
charset=3Diso-8859-1">
<META content=3D"MSHTML 6.00.6000.16587" name=3DGENERATOR>
<STYLE></STYLE>
</HEAD>
<BODY bgColor=3D#ffffff>
<DIV><FONT face=3DArial size=3D2>Plain Text - no html=20
markup.</FONT></DIV></BODY></HTML>

------=_NextPart_000_0022_01C8E34D.2DE023B0--

