/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.sysbliss.jira.plugins.workflow.model.layout {
    public interface AnnotationLayout extends AnnotationLayoutBase {
    }
}