/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.sysbliss.jira.plugins.workflow.model.layout {

    [Bindable]
    [RemoteClass(alias="com.sysbliss.jira.plugins.workflow.model.layout.AnnotationLayoutImpl")]
    public class AnnotationLayoutImpl extends AnnotationLayoutImplBase implements AnnotationLayout {
    }
}