/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.sysbliss.jira.plugins.workflow.model.layout {

    import mx.collections.ArrayCollection;

    [Bindable]
    [RemoteClass(alias="com.sysbliss.jira.plugins.workflow.model.layout.EdgeLayoutImpl")]
    public class EdgeLayoutImpl extends EdgeLayoutImplBase implements EdgeLayout {

        public function EdgeLayoutImpl()
		{
			super();
			_controlPoints = new ArrayCollection();
            _labelPoint = new LayoutPointImpl();
            _labelPoint.x = -200;
            _labelPoint.y = -200;
		}
        
        override public function get allPoints():ArrayCollection
		{
			var tmp:ArrayCollection = new ArrayCollection();
			tmp.source.push(_startPoint);
			tmp.source = tmp.source.concat(_controlPoints);
			tmp.source.push(_endPoint);

			return tmp;
		}
    }
}