/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.sysbliss.jira.plugins.workflow.model.layout {
import mx.collections.ArrayCollection;

[Bindable]
    [RemoteClass(alias="com.sysbliss.jira.plugins.workflow.model.layout.NodeLayoutImpl")]
    public class NodeLayoutImpl extends NodeLayoutImplBase implements NodeLayout {


    public function NodeLayoutImpl()
    {
        super();
			_isInitialAction = false;
			_inLinks = new ArrayCollection();
			_outLinks = new ArrayCollection();
    }


    }
}