Return-Path: jirauser@atlassian.com
Received: from mail.atlassian.com (LHLO mail.atlassian.com) (63.246.22.40)
 by mail.atlassian.com with LMTP; Sun, 13 Jul 2008 18:41:19 -0500 (CDT)
Received: from [192.168.3.238] (unknown [203.63.130.33])
	by mail.atlassian.com (Postfix) with ESMTP id B18EC16324C7
	for <jirauser@atlassian.com>; Sun, 13 Jul 2008 18:41:18 -0500 (CDT)
Message-Id: <A6615E19-AC1D-465B-B511-7ECB6579F8EE@atlassian.com>
From: Jira test user <jirauser@atlassian.com>
To: jirauser@atlassian.com
Content-Type: multipart/alternative; boundary=Apple-Mail-21--685414043
Mime-Version: 1.0 (Apple Message framework v924)
Subject: AppleMailHtml
Date: Mon, 14 Jul 2008 09:41:10 +1000
X-Mailer: Apple Mail (2.924)


--Apple-Mail-21--685414043
Content-Type: text/plain;
	charset=US-ASCII;
	format=flowed
Content-Transfer-Encoding: 7bit

Html email

BOLD

Plain

Italics

Underline

Big Font
--Apple-Mail-21--685414043
Content-Type: text/html;
	charset=US-ASCII
Content-Transfer-Encoding: 7bit

<html><body style="word-wrap: break-word; -webkit-nbsp-mode: space; -webkit-line-break: after-white-space; ">Html email<div><br></div><div><b>BOLD</b></div><div><br></div><div>Plain</div><div><br></div><div><i>Italics</i></div><div><br></div><div><span class="Apple-style-span" style="text-decoration: underline;">Underline</span></div><div><span class="Apple-style-span" style="text-decoration: underline;"><br></span></div><div><span class="Apple-style-span" style="text-decoration: underline;"><font class="Apple-style-span" face="'Gill Sans'" size="7"><span class="Apple-style-span" style="font-size: 36px;"><b>Big Font</b></span></font></span></div></body></html>
--Apple-Mail-21--685414043--
