Return-Path: jirauser@atlassian.com
Received: from mail.atlassian.com (LHLO mail.atlassian.com) (63.246.22.40)
 by mail.atlassian.com with LMTP; Sun, 13 Jul 2008 18:42:36 -0500 (CDT)
Received: from [192.168.3.238] (unknown [203.63.130.33])
	by mail.atlassian.com (Postfix) with ESMTP id 3B2E916324F2
	for <jirauser@atlassian.com>; Sun, 13 Jul 2008 18:42:35 -0500 (CDT)
Message-Id: <0B21CD49-0E39-417B-8F2E-1C0206AA4911@atlassian.com>
From: Jira test user <jirauser@atlassian.com>
To: jirauser@atlassian.com
Content-Type: text/plain; charset=US-ASCII; format=flowed
Content-Transfer-Encoding: 7bit
Mime-Version: 1.0 (Apple Message framework v924)
Subject: Apple mail Plain Text
Date: Mon, 14 Jul 2008 09:42:27 +1000
X-Mailer: Apple Mail (2.924)

Plain

Was Bold

Was Underlined
