Return-Path: jpendleton@atlassian.com
Received: from mail.atlassian.com (LHLO mail.atlassian.com) (63.246.22.40)
 by mail.atlassian.com with LMTP; Wed, 23 Jul 2008 01:10:59 -0500 (CDT)
Received: from Justuss-Mac.sydney.atlassian.com (unknown [203.63.130.33])
	by mail.atlassian.com (Postfix) with ESMTP id AC3A33EB2B6
	for <mpokorny@atlassian.com>; Wed, 23 Jul 2008 01:10:58 -0500 (CDT)
Message-Id: <FEDDBABB-79E0-4DC7-B51F-5133C9D4687E@atlassian.com>
From: Justus Pendleton <jpendleton@atlassian.com>
To: mpokorny@atlassian.com
Content-Type: multipart/mixed; boundary=Apple-Mail-22-115570846
Mime-Version: 1.0 (Apple Message framework v926)
Subject: AppleMailWithPlainTextAttachment
Date: Wed, 23 Jul 2008 16:10:55 +1000
X-Mailer: Apple Mail (2.926)


--Apple-Mail-22-115570846
Content-Disposition: attachment;
	filename=plain.txt
Content-Type: text/plain;
	x-unix-mode=0644;
	name="plain.txt"
Content-Transfer-Encoding: 7bit

-> Plain Text attachment

--Apple-Mail-22-115570846
Content-Type: text/plain;
	charset=US-ASCII;
	format=flowed
Content-Transfer-Encoding: 7bit

also has Plain Text attachment
--Apple-Mail-22-115570846--
