Return-Path: jpendleton@atlassian.com
Received: from mail.atlassian.com (LHLO mail.atlassian.com) (63.246.22.40)
 by mail.atlassian.com with LMTP; Wed, 23 Jul 2008 01:11:43 -0500 (CDT)
Received: from Justuss-Mac.sydney.atlassian.com (unknown [203.63.130.33])
	by mail.atlassian.com (Postfix) with ESMTP id 164B63EB32F
	for <mpokorny@atlassian.com>; Wed, 23 Jul 2008 01:11:42 -0500 (CDT)
Message-Id: <5A80BEB9-61B5-4C78-A2DC-61E14BE2A76E@atlassian.com>
From: Justus Pendleton <jpendleton@atlassian.com>
To: mpokorny@atlassian.com
Content-Type: multipart/mixed; boundary=Apple-Mail-23-115617773
Mime-Version: 1.0 (Apple Message framework v926)
Subject: AppleMailHtmlWithHtmlFileAttachment
Date: Wed, 23 Jul 2008 16:11:42 +1000
X-Mailer: Apple Mail (2.926)


--Apple-Mail-23-115617773
Content-Disposition: attachment;
	filename=page.html
Content-Type: text/html;
	x-unix-mode=0644;
	name="page.html"
Content-Transfer-Encoding: 7bit

<html>
<body>
Html attachment
</body>
</html>

--Apple-Mail-23-115617773
Content-Type: text/plain;
	charset=US-ASCII;
	format=flowed
Content-Transfer-Encoding: 7bit

Also has html attachment

--Apple-Mail-23-115617773--
