Return-Path: jira-test@atlassian.com
Received: from mail.atlassian.com (LHLO mail.atlassian.com) (63.246.22.40)
 by mail.atlassian.com with LMTP; Tue, 29 Jul 2008 23:20:46 -0500 (CDT)
Received: from [192.168.168.129] (unknown [203.63.130.33])
	by mail.atlassian.com (Postfix) with ESMTP id 468F7378C5E
	for <mpokorny@atlassian.com>; Tue, 29 Jul 2008 23:20:45 -0500 (CDT)
Subject: EvolutionPlainTextWithPlainTextAttachment
From: JIRA Test <jira-test@atlassian.com>
To: mpokorny@atlassian.com
Content-Type: multipart/mixed; boundary="=-LZFUIY+G4toexx7ZWx3X"
Date: Fri, 13 Jun 2008 22:38:39 +1000
Message-Id: <1213360719.16444.11.camel@atlassian-desktop>
Mime-Version: 1.0
X-Mailer: Evolution 2.6.1


--=-LZFUIY+G4toexx7ZWx3X
Content-Type: text/plain
Content-Transfer-Encoding: 7bit

Plain text in message

Plain text attachment should follow

--=-LZFUIY+G4toexx7ZWx3X
Content-Disposition: attachment; filename=plain.txt
Content-Type: text/plain; name=plain.txt; charset=UTF-8
Content-Transfer-Encoding: 7bit

This is a plain text file!

--=-LZFUIY+G4toexx7ZWx3X--

