Return-Path: jirauser@atlassian.com
Received: from mail.atlassian.com (LHLO mail.atlassian.com) (63.246.22.40)
 by mail.atlassian.com with LMTP; Thu, 10 Jul 2008 21:46:40 -0500 (CDT)
Received: from [192.168.0.172] (unknown [203.63.130.33])
	by mail.atlassian.com (Postfix) with ESMTP id C1F4516331B0
	for <jirauser@atlassian.com>; Thu, 10 Jul 2008 21:46:39 -0500 (CDT)
Subject: Evolution Html InlineImage
From: JIRA TEST USER <jirauser@atlassian.com>
To: JIRA TEST USER <jirauser@atlassian.com>
Content-Type: multipart/related; type="multipart/alternative"; boundary="=-jj4Z1sY5W5M61PXITEkJ"
Date: Fri, 11 Jul 2008 12:46:25 +1000
Message-Id: <1215744385.4507.77.camel@carltondraught>
Mime-Version: 1.0
X-Mailer: Evolution 2.22.2 


--=-jj4Z1sY5W5M61PXITEkJ
Content-Type: multipart/alternative; boundary="=-gedwZ/GgycN+S10yntMv"


--=-gedwZ/GgycN+S10yntMv
Content-Type: text/plain; 
Content-Transfer-Encoding: 8bit

Before Image (bold)  After image(italics)


--=-gedwZ/GgycN+S10yntMv
Content-Type: text/html; 
Content-Transfer-Encoding: 7bit

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 TRANSITIONAL//EN">
<HTML>
<HEAD>
  <META HTTP-EQUIV="Content-Type" CONTENT="text/html; ">
  <META NAME="GENERATOR" CONTENT="GtkHTML/3.18.2">
</HEAD>
<BODY>
<B>Before Image (bold) </B><IMG SRC="cid:1215744383.4507.75.camel@carltondraught" ALIGN="bottom" BORDER="0"><B> </B><B><I>After image(italics)</I></B><B></B><BR>
<TABLE CELLSPACING="0" CELLPADDING="0" WIDTH="100%">
<TR>
<TD>
<BR>
</TD>
</TR>
</TABLE>
</BODY>
</HTML>

--=-gedwZ/GgycN+S10yntMv--

--=-jj4Z1sY5W5M61PXITEkJ
Content-ID: <1215744383.4507.75.camel@carltondraught>
Content-Disposition: attachment; filename=image.jpeg
Content-Type: image/jpeg; name=image.jpeg
Content-Transfer-Encoding: base64

R0lGODlhTwBOAKUhAAsLBSMbEx4pDC0sFjUwKUUwJTNEHThTKFBLME1NTWtTOWpXRlFsMXpmUFWA
O2R/NnV1dY50WG+KOph+YZyAXqZ+TqR6aZuBYqiEWaaHY5OTk8qSe72gfbWlkt6dgfCaduafgf//
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////yH+FUNyZWF0ZWQgd2l0aCBUaGUgR0lN
UAAh+QQBCgA/ACwAAAAATwBOAAAG/sCQcEgsGo/IpHLJbDqf0Kh0Sq1ar9isdsvter9VgViACAkG
DAF4LRRfKvAGYADHqNleAQPO59Mrd3hbAhJ9hhgDAIJYZ2MChpARiothEXwADZAVAJydnIGUT4+a
hhkZGJCgoU2jpK58qqtKaQJvr6R2sqIBt665ukytvZoZcwOJBsBFwsN1EQXHFiAfHx6Sx8pizXAZ
xwMKG9Ti49TYqwDMt8fh5O3jCAOrApbNAwju+OMS8ZQAzYgR8gksRykdqW7sBuIDwQ8Ppwy9ECkU
2C2Uv14DLLTbsCBAgY8gQ35MdK5XhAHjNnysIG3gpFAGDV1A+SEDyIQKF7wURIYP/gYCmgBY2ABg
wbSJ4xouAoCAj05InAgQSJBAJ6cCFp4t8IBvQDKYTeEAmAD1KoIGF0xdODnJ2zFjAw7IEgYAFYaw
3FxdkKsMCd5NcS72ItAXCQB6FYqJhTiMcGEj8/jIEbvN8WMiwghkwiAY42XMhS6hQgC02c7LzC6O
3Xa6cKI+kiiz/jykMwCIFzr3at23Vp+LCBZsq2AZNWzVqLY14PuY0296unsV+zznN6rcwytM4K1r
AGPZBIQPzxALmDDFm75vK6+rc4Ow0Yexl9V5gCX0w381t14hdvbpj712CRwI/NVMBPOVBId/t2VX
AQLMFSYYAdA5CAhtANjS4GTZ/iFIiQFiJFGXWKhk6GCCXAiAih6GqSbbcGQs0op+mBFAh00vNtMA
ilMwYMRhfZT3CGcmcjbeAGdwsY9SIfgjCVk0hpBGBQxwYld8pChQQFMxarHHA0QwkIkio6QxxJQX
qliBkSYBGRaLWewRgQRDPLJAMq3Qokdi2AgAEWeIaYLIAAlkEIEC9m2yhQEXSklHIAYNEEByhlj1
XQQdVTcAKnQkwskgFUggAIiJvaSNT0XxYaiq3BwjRhlCCEdHBE3BysUBoySnCgICLMCrGkiekahY
TMGhCjpAavrFnsbyWJtPCmxSADpfFeEksExugSSv2SYxSgEVdOBPAwRwF8IA2xx0exkAhQCgAAZs
omMYBxWoG2Co2hTjzwI+/hgCBwHQSRsRnZpRwQIQSCKAA0YM0K5juKJBgACf9mXOI94p2vAeniCA
2E9UmSsPPP215vCChpx0THAafBIXAxF64cmxTXniSSawUaCJVDZ7okXPQHtyV9BEezLAAp72XFwW
RXsinCeaLVAAAQh81PTVM0uBdc+b2JfBBRr8uSBZ220NCgOJxCzi1kRHokEEDSjQgCUnbVL00lb0
rHbQ4HID9wILUJVcuXZjXdgBCDyQpBFLmhPzAUmrPfDklEsRBAA7


--=-jj4Z1sY5W5M61PXITEkJ--

