Return-Path: brad.baker@atlassian.com
Received: from mail.atlassian.com (LHLO mail.atlassian.com) (63.246.22.40)
 by mail.atlassian.com with LMTP; Wed, 23 Jul 2008 01:15:23 -0500 (CDT)
Received: from [192.168.0.172] (unknown [203.63.130.33])
	by mail.atlassian.com (Postfix) with ESMTP id BD6AD3EB4A6
	for <mpokorny@atlassian.com>; Wed, 23 Jul 2008 01:15:22 -0500 (CDT)
Subject: EvolutionHtmlWithHtmlAttachment
From: Brad Baker <brad.baker@atlassian.com>
To: Miroslav Pokorny <mpokorny@atlassian.com>
Content-Type: multipart/mixed; boundary="=-e9b77xrg+uM43oLeZk90"
Date: Wed, 23 Jul 2008 16:15:08 +1000
Message-Id: <1216793708.9022.6.camel@carltondraught>
Mime-Version: 1.0
X-Mailer: Evolution 2.22.3.1 


--=-e9b77xrg+uM43oLeZk90
Content-Type: multipart/alternative; boundary="=-jiRwnsxl2t05mU48S1CH"


--=-jiRwnsxl2t05mU48S1CH
Content-Type: text/plain
Content-Transfer-Encoding: 7bit


Also has a html attachment

--=-jiRwnsxl2t05mU48S1CH
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 7bit

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 TRANSITIONAL//EN">
<HTML>
<HEAD>
  <META HTTP-EQUIV="Content-Type" CONTENT="text/html; CHARSET=UTF-8">
  <META NAME="GENERATOR" CONTENT="GtkHTML/3.18.2">
</HEAD>
<BODY>
<TABLE CELLSPACING="0" CELLPADDING="0" WIDTH="100%">
<TR>
<TD>
<BR>
</TD>
</TR>
</TABLE>
with noise
</BODY>
</HTML>

--=-jiRwnsxl2t05mU48S1CH--

--=-e9b77xrg+uM43oLeZk90
Content-Disposition: attachment; filename=page.html
Content-Type: text/html; name=page.html; charset=UTF-8
Content-Transfer-Encoding: 7bit

<html>
<body>
html content !!!!
</body>
</html>

--=-e9b77xrg+uM43oLeZk90--

