Return-Path: jirauser@gmail.com
Received: from mail.atlassian.com (LHLO mail.atlassian.com) (63.246.22.40)
 by mail.atlassian.com with LMTP; Thu, 10 Jul 2008 21:16:13 -0500 (CDT)
Received: from p02c11m082.mxlogic.net (mxl144v245.mxlogic.net [208.65.144.245])
	by mail.atlassian.com (Postfix) with ESMTP id 0DE4F16324F2
	for <jirauser@atlassian.com>; Thu, 10 Jul 2008 21:16:13 -0500 (CDT)
Received: from unknown [209.85.142.187] (EHLO ti-out-0910.google.com)
	by p02c11m082.mxlogic.net (mxl_mta-5.6.0-1)
	with ESMTP id c62c6784.3592358832.4498.00-083.p02c11m082.mxlogic.net (envelope-from <jirauser@gmail.com>);
	Thu, 10 Jul 2008 20:16:12 -0600 (MDT)
Received: by ti-out-0910.google.com with SMTP id w7so1647267tib.13
        for <jirauser@atlassian.com>; Thu, 10 Jul 2008 19:16:11 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=gamma;
        h=domainkey-signature:received:received:message-id:date:from:to
         :subject:mime-version:content-type;
        bh=v+bORUy+jmN+RUytbrjuba+oeG3Sz676BBybnr1HaIE=;
        b=PJ8SPhrMfbogwf1wkBqxU8KXVuoHXKTigrUi8yQKoNwiRYYLdtHWQUsTPsITAU8hAq
         1sgK2LnTkvVEKNyXTqBUCHQiE238IwZO8/5BO02uliB4KiM56WC19+Azy8WGYrftbK7a
         TitlfwKJBcvmOvIa4fsdeoIAns2+7nf/RP59E=
DomainKey-Signature: a=rsa-sha1; c=nofws;
        d=gmail.com; s=gamma;
        h=message-id:date:from:to:subject:mime-version:content-type;
        b=LPW2dgbIwssvv+ORCnDnAgk8QySseUjn5Np6fTWyrhLTppHmWN5lVrZXNF8jDOnPGz
         A5bWxDGQu+xARoCPngxMvS9KoIPo71ys99Pojwjvx0/1Jb5n7KINzH/k7QzglPg6Keem
         eJpkCS9IACDjBU7fvXvUxNrRrRivy7Zx3Ypjw=
Received: by 10.110.15.19 with SMTP id 19mr5511180tio.42.1215742570647;
        Thu, 10 Jul 2008 19:16:10 -0700 (PDT)
Received: by 10.110.39.16 with HTTP; Thu, 10 Jul 2008 19:16:10 -0700 (PDT)
Message-ID: <3ba4a7240807101916u221563cck5033326ab25a2859@mail.gmail.com>
Date: Fri, 11 Jul 2008 12:16:10 +1000
From: "JIRA TEST USER" <jirauser@gmail.com>
To: jirauser@atlassian.com
Subject: Gmail Html ImageAttached
MIME-Version: 1.0
Content-Type: multipart/mixed; 
	boundary="----=_Part_45661_11413174.1215742570635"
X-Spam: [F=0.0117722861; B=0.500(0); spf=0.500; CM=0.500; MH=0.500(2008071035); R=0.096(108610195529); S=0.100(2008062001); SS=0.500; SC=none]
X-MAIL-FROM: <jirauser@gmail.com>
X-SOURCE-IP: [209.85.142.187]
X-AnalysisOut: [v=1.0 c=1 a=VUvnqsgs1WA4keTt7pUA:9 a=DUxLZnoV5fxNfHSCVEg1Y]
X-AnalysisOut: [xsh2-QA:4 a=yGn54wW5l98A:10 a=YHBVt9a8oYpsn7DXnw0A:9 a=B0o]
X-AnalysisOut: [ayYojRS71udunh7TB_jBKlOMA:4 a=YGxRMErdduYA:10 a=CJPn12L1VJ]
X-AnalysisOut: [5qqv_ViR8A:9 a=wKbvbaRfYCKVaIy8MQ_Z8aDeJGUA:4 a=bC4pTEGzVW]
X-AnalysisOut: [IA:10 a=KQqxNPgzF0kA:10 a=iSihqw3xtoJRpbjf:18]

------=_Part_45661_11413174.1215742570635
Content-Type: multipart/alternative; 
	boundary="----=_Part_45662_27408239.1215742570635"

------=_Part_45662_27408239.1215742570635
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: 7bit
Content-Disposition: inline

*BOLD

**Italics**

**Underlined**
*

------=_Part_45662_27408239.1215742570635
Content-Type: text/html; charset=ISO-8859-1
Content-Transfer-Encoding: 7bit
Content-Disposition: inline

<b>BOLD<br>
<br>
</b><i>Italics</i><b><br>
<br>
</b><u>Underlined</u><b><br>
</b><br>-- <br>mP<br><br>

------=_Part_45662_27408239.1215742570635--

------=_Part_45661_11413174.1215742570635
Content-Type: image/jpeg; name=image.jpeg
Content-Transfer-Encoding: base64
X-Attachment-Id: f_fii5pskc0
Content-Disposition: attachment; filename=image.jpeg

/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAd
Hx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5Ojf/2wBDAQoKCg0MDRoPDxo3JR8lNzc3Nzc3
Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzf/wAARCACWAG8DASIA
AhEBAxEB/8QAHAAAAAcBAQAAAAAAAAAAAAAAAAEDBAUGBwII/8QAQhAAAQIEAgYGBgcHBQEAAAAA
AQIDAAQFESFBBhIxUWFxEyKBkaGxByMywdHwFBdSVmKT0hU0NUJUcoIkM1N0kuH/xAAaAQACAwEB
AAAAAAAAAAAAAAAEBgIDBQAB/8QAMREAAQMCAwYEBgIDAAAAAAAAAQACAwQRBRIhFDEyQXGRE1Jh
8CIjUYHB0TThM7Hx/9oADAMBAAIRAxEAPwDboKBAjlyEJvvsyzRdmHUNtp2qWqwERWkGkMvR29Sw
dmlC6GgdnFW4ecZ3UqnOVR7pZx0rN+qgYJRyEZ1XiMdP8I1d73rSo8NkqPiOjf8AfRXOo6bSbBKJ
Flcyofzq6ifie4RX5rTGrvE9G42wnc22L96rxAZ2gRhy4jUSHit00W9Fh1NEOG/XX+lIrrtWWSVV
Ga/xcI8oNuv1ds3TUZj/ACVrecRsAwN48t75j3KJ8CK1so7BWST00qjJAmAzMJz1k6p7x8IslM0v
p04Qh8mUdOTh6p/y+Nozftg4LhxKojOpuPVCTYZTSjRtj6e7LZwQoAg3BxBGcdRllE0gnaQoJQrp
Ze/WZWcOw5GNGpVTlarLB+VXcbFIPtIO4iN6kro6kWGh+iX6ugkpjc6t+qewIEFBqBRxDaTVtFHk
+pZU07cNIOX4jwHjErMPIl2XHnlarbaSpR3ARk9XqDtUn3Zp0EaxshP2E5D54xnYjV7PHZvEfd1o
4bR7RJd3CPdk1fedfdW8+4pbizdSlbSYTg44ecQyguOqCUjaVGFbVx9U2aNC7wgs4ipitJTcS6Nb
8S8PDbDFEzUJ18NNOOqWs9RtrAnlbGC46GV+p0QcldEzdqrJAvjElQdA3XEh+tzUwknYw28q45qv
5RE6T6PVKgLMxKzD70gTgvXKi3wUDcdsWHD38iqhicZNiEpAtEJL1l0WDyA4DmMD8PKJaWmmpgEt
KxGJScFDs9+yBZYJIuIIuKojk4Slc9sPKXUZilzaZmWVYjBST7KxuMNOyBe0VNe5jg5p1Ctc0PaW
uFwVrtLqDFTkm5qXPVVgUnak5gw7jNdD6sadUksuqtLzBCV32JVkr3cjwjSYbqKqFTFm5jek+upT
TS5RuO5VbT6f6GQakkGyphV1f2p+Jt3RQOMT+m0yX6+6i/VZQlsd1z4mIHshdxGUyVLvTTsmPDoh
FTN9de6RmphqVZU88SEjLMnIDjFbnZt2bcK3cEA2SgZCHdZeLqrg2QlZQ2DsNvaV39XsO+ItIGV/
eqC6GANbnO9C105c7INyfUemTNXnm5WSbU4tRxUEkhI3m0a7o9o1L0GXGpLuqfI9Y+pFyeVtghf0
f0FFGojbi0ATUyAtwnaBkItEbIpgRqdVhvqCTpuUQCFC6TcHO+EE4hDjakOJStChZSVC4IzvDydY
A9cgWJPXAz4847Yk0ABTyQte44hPL4xVs7s1l74wy3WNaa6LilOGdp9lyDiusB1iyd3LceznWGnV
tLSUL1SMQQbHs+e+PRk7ISk9LOS80w2404kpUCkbDxyjz7WqeulVebkHCSWHSnWOGGR7RYx5LDlG
uoV0M+Y+ql6dO/SUBLlg5a4IGChnhkdlxxGRh73RWqYVKmC1rWUrFKyMAsDA+YO8ExYJd0PMpc1N
VWIUm/sqBsR3gwu1cAifpuTHSTGVmu9KxqmjU+ajR5d9aruAajh/EML9uB7YyrDlF19Hcz1ZyVJw
Gq4keB90F4TKWT5eTkLi8QfT5+bf+Ks19WvXJ9R/qFjuNojZhzoZd13/AI0FWPAXiS0gBbrk+k/1
Cz3m/viHqP7hM4bG1eUAyC85B+v5R0ZtACPp+FCVVvoVS8viromUg8Tjc9sFSW0u1aTStI1FPIBv
zhavXE7rZFAz24mGUm6JeZZeF7trSq3I3jcpT8tpKw6sfMcAvSaUhCQlIsEiwEVmsVfSKV0wpVPp
9GExSJhN5qcx9Ubm+N7JsADiDrXsIsUo8mYlWXkm6XEBQPMQrGysRN53WKWUpJGs8gEjcDfxtbth
vX6omi0Wdqa2HX0yrJcLTQ6yrfO3KHEw+ErSlJ2G6vhDgG4uIi14cSByUi0gXURonXE6SUCUqzcs
7LJmAr1TmJFlEYHMG1wd0Zt6XJMS+kLM0kYTMuCoDMpNj4asbBsEZN6YZxt2ryUolQCmGSpar7Co
4DuTftiE9shVkH+QKjSq9WaZVucTa2WMWFo9HOvt/wAq0pdHP2T5J74rsqgqmWkpwu4m+/bFicJ/
aTNs2XL/APpuF2v1cB6H9pjoNGk+oTrvix6AuFNdKBsWwoHsIPuiufOyLFoGkmvAgYJZVfhsgag/
ks6omv8A4z+iS05lixX3HLdV9CXB3WPlFecQlxtSHBdKklKuRjQfSBIF6ntTiE3VLqsr+1XwNu+M
/vleJ4hEY6l3rr3UcOlEtM3007f0oSfQt6nsPKxdZ9U6dxGBPePGI0cTY7xFieSlp5SlgFh+yXAd
gVawPIiw7BviKn6e7LFS20qW1lmU84JpJ22yH7fpC1lO6+cff9rTPRrpMJmmilzH7xLDqXVipH/y
Lg5NrWLJASN4OMefJObekZtqZlnC2+g3SqNd0W0nlq6wEEpanEi62b7eKeHlGmZX2tdY7omg3sp/
PjDiXmOjGqu+rkd0N4Z1WqydJlTMz7yW0DADapR3AZmIMcWm4XjmhwsVKVSqStMpz89MuDomk3IB
xUcgOJOEef6tUHqnUpifmTrOvrKlJubJ3AchYRKaVaTTGkD4FizJtm7bN7kn7St58B4xBIQpakoQ
FXOwDOLJJi8aqcUOTqntFZ6WdCziGhra2HIfPCJhv1lQeXbBptLY5nrHw1ISlkJpsn1k6ziiOqk4
rWdiR87zDiUZLLIStQU4SVOKGxSjiTy3cLQv1MokeXDduCYqaIxsDTv3lLX4xcvR3LkuTkzkEpbB
54nyEU23KNQ0TkDIUVlC02cc9YvmdnhaCcIizz5+TfyhcXmDIMnN341UrMMtzLDjLyQptxJSpJzB
jJKxTnaXPuyroJ1TdCvtJOw/Od416IfSahorMnZNkzTVy0s5/hPA+Ea+I0m0R3bxD3ZZOG1mzyWd
wn3dZWtKVpUhaQpKgQQRgRuhsFrlMHSpbA9l04lHBXD8XfvL11C2nFIcSUrSbKSoWIMcjhCvct0I
TXo7UJk/T5WYGukaijiFtnb7obt02YlnkvSczqOJN0qxSQeYh6ZYIJMsssE4lKQCgnin4WMALmke
2wl3i0u3gq3mYIZUSs0a7uhpKaJ/E3sp1rTSptSv0R1iXdqGrdLpUQkjeRa19uFxex3RU6g1VqnN
KmJ1ZedVhdaxYDcBkOAhRuZ19R4svAuP3HUv1QCBa18hftMPPpCj7Ms+TxCU+Zgh1XM3kEKyigNz
r7+yjGqM8r/ecShP4cTD9DUrTkggHXXgmw1lrO4D54x3/q3Ba7bA4ddXjYDxjtiXbaUpQ1lOKFlO
LN1HhfdwGEDSTvfo8/Ye/wBoqOnYzVg+59/pcsMrW8JiZADguG0A3DYO3mo5nsGZLmBaHEhJPT80
3LS6NZaz2AbzwigB0rg1o1VznNjaXOOgUlopSjU6kgrTeXZIW4cjuHbGnQxo1MapUiiWaxO1a81K
3w+htoqUU0Qbz5pQrao1Mpdy5I4Z1afbplPem3cQgdVN/aUdg74dxQvSBUC7OtSCFdRka6wM1HZ3
Dzj2sqPAhL+fLquoqfaJgzlz6KrTbzs1MuzLqtZ1xRUvcT7oSCr4ZjIx3BKSFbReFAuJNynIAAWC
KEpnpOgUGQOkIsk39knC/Zt7IU1VA4G/AwLnNJHZeOBsbrjqE3dQloSqEiyEOJSBw1VAe6HJhGZU
yWVF9WqhNlEnC1je/hCusDhj3GPTqAvALEo4F8YK5OxPfhB6pPtK7BEVJAKxsBffwic0TqQptWQX
CAy96twnK+w9h8LxCgBIAAsIOJxSmJ4e3eFVNE2VhY7cVtECIjRefNQorDizd1A6Nw8U59ose2Ja
HSN4kYHjcUkyRmN5Yd4QjHalOpnqpMv66SXHVKA1sbXw8LRYPS3WZiUlpSmyzqmxMhS39U2KkCwC
b7iSb8oym9rG9gSDfZaM7EIvHsy9rLSw6XZ7vte6tbruo6y2BcuKI5AJJJ8AO2FbRCUVTz83rOOL
WhlBAKscVFOfJPjE3aF6eLwnZOaYoJfFbn5IQMIO0AxQrk1qn8OmLfYMOle0ecNamL09/wDt98Oj
tPOJngHU/hRHGeg/KKDygQIgpJKYdDDJcIwSRflcAmFM4b1FBXITCBe6m1DDbsitvzUw+QHHlqBN
7E4Hj874Lp6UzC4NrISoqhCbEXutg9HUxjOyxVh1XEjvB90XSPPujNcmNH6mzOsKUWwdV5obFovi
PC4O+0egULS4hK0G6VC4IzBhloW5IhHe9ks1zs8xkta6p3pF0VmK+zLzVO1TOSwKejUbBxJxsDkQ
dnMxlg0erKZkMfsqdDqjYpLKsO21s49DQMoufC1xuqWTuaLLIkaJ1SjU8Lfl7ot0jikEEI4HlDK9
zGs6RfwGof8AXX5Rkt8YXcUp2xSgt56pkwqd00JDuWi6gRzB2jMWom9S/cXhwHmIcm9zCT7aXm1N
qJsbXtzvHZJJiRPwge+SiB8RPvmjvB3jmBEbKS6vxiCqlMeYK5sS6/oqlXDwSdUKJvYn52xaKKlK
6xIpUAoGYbuDn1hGuFKSjUKQUkWKSMI2MKp8+Z9/RYuLVHh5WZb8151pFLnKvNplpBlTrqjZRAwQ
N5OQj0JIS/0SRl5bW1uhaS3rb7AD3R2wwzLpKZdptpJNyG0hIPdCsb0cQjWBLKZCigQIEWqpVTTm
g6SVxDTWj9ebprOopEw0tgK6W+zGxIwvhFGPot02y0qkzzZP6YECIPijfq5oPUKxk0jBZjiOhRfV
bpv96ZL8o/pgD0W6b/emS/KP6YECIbNB5B2CntM/nPcofVbpt96ZP8o/pgx6LdNc9KpP8k/pgQI7
ZoPIOwXbTP5z3KH1Waa/eqU/JP6YH1WaafeuV/JPwgQI92aHyDsF20z+c9yu2fRhpuw6h1rS2VS4
hQUlQZOBGIOyNVo0vOytKlWKnNibnG2gl6YCNUOKzNoECJtjYzRoA6Kt8j36vJPVPIECBElBf//Z

------=_Part_45661_11413174.1215742570635--
