Return-Path: jirauser@gmail.com
Received: from mail.atlassian.com (LHLO mail.atlassian.com) (63.246.22.40)
 by mail.atlassian.com with LMTP; Thu, 10 Jul 2008 21:14:20 -0500 (CDT)
Received: from p02c11m084.mxlogic.net (mxl144v245.mxlogic.net [208.65.144.245])
	by mail.atlassian.com (Postfix) with ESMTP id 519DB16324F2
	for <jirauser@atlassian.com>; Thu, 10 Jul 2008 21:14:20 -0500 (CDT)
Received: from unknown [209.85.142.184] (EHLO ti-out-0910.google.com)
	by p02c11m084.mxlogic.net (mxl_mta-5.6.0-1)
	with ESMTP id bf1c6784.3309788080.235900.00-018.p02c11m084.mxlogic.net (envelope-from <jirauser@gmail.com>);
	Thu, 10 Jul 2008 20:14:19 -0600 (MDT)
Received: by ti-out-0910.google.com with SMTP id w7so1646803tib.13
        for <jirauser@atlassian.com>; Thu, 10 Jul 2008 19:14:18 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=gamma;
        h=domainkey-signature:received:received:message-id:date:from:to
         :subject:mime-version:content-type:content-transfer-encoding
         :content-disposition;
        bh=jwJ98yvMwWPflHH/89AzaX6WsnD8pOOCIOennq/Yt+s=;
        b=pvqF3+VVGJLpVuzEf7YaDp0YDrC5BOfUwfwxf+gMDkH5/Yvt1l5i+e0QAalHj2BGzp
         iP0e1Q6OnSlGCU27uZIZWk9RSWUy9oIjjHBfAYgAuLxEnnHKzmpqYla27IowZDdieU+N
         ifynuPWoHHeFCflU5XBSX2Yz38oArtJL1DAUQ=
DomainKey-Signature: a=rsa-sha1; c=nofws;
        d=gmail.com; s=gamma;
        h=message-id:date:from:to:subject:mime-version:content-type
         :content-transfer-encoding:content-disposition;
        b=AUIfsbtIMPGfYIWEwlDUSnKcWcksHImZZqXCzp2BB8WkXAucF211z+KZpsgeQ93DGg
         YLCM8D42R8xM6Sa9yWPHnqHwL5LhJza3v3IVnMCi8byzCpzN3hHmVWMYnUDCl56gMSmS
         pvpMC2+fIWDafO8t1O6yVOUlTQ4zqpFt0VXtY=
Received: by 10.110.20.17 with SMTP id 17mr5509701tit.12.1215742458240;
        Thu, 10 Jul 2008 19:14:18 -0700 (PDT)
Received: by 10.110.39.16 with HTTP; Thu, 10 Jul 2008 19:14:18 -0700 (PDT)
Message-ID: <3ba4a7240807101914v470dfbcbp47993e3927ead793@mail.gmail.com>
Date: Fri, 11 Jul 2008 12:14:18 +1000
From: "JIRA TEST USER" <jirauser@gmail.com>
To: jirauser@atlassian.com
Subject: Gmail PlainText
MIME-Version: 1.0
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: 7bit
Content-Disposition: inline
X-Spam: [F=0.0217927158; B=0.500(0); spf=0.500; CM=0.500; MH=0.650(2008071035); R=0.097(108610195529); S=0.100(2008062001); SS=0.500; SC=none]
X-MAIL-FROM: <jirauser@gmail.com>
X-SOURCE-IP: [209.85.142.184]
X-AnalysisOut: [v=1.0 c=1 a=42g5KpNRyzwoOpYof74A:9 a=Sm6rqkuvaPSZJgpYfmJBp]
X-AnalysisOut: [nz_XuUA:4 a=BgJWR2bEJjkA:10]

Plain Text from Gmail.

