Return-Path: miroslav.pokorny@gmail.com
Received: from mail.atlassian.com (LHLO mail.atlassian.com) (63.246.22.40)
 by mail.atlassian.com with LMTP; Wed, 23 Jul 2008 01:05:16 -0500 (CDT)
Received: from p02c11m115.mxlogic.net (mxl144v245.mxlogic.net [208.65.144.245])
	by mail.atlassian.com (Postfix) with ESMTP id D84213EAFCC
	for <mpokorny@atlassian.com>; Wed, 23 Jul 2008 01:05:16 -0500 (CDT)
Received: from unknown [209.85.142.191] (EHLO ti-out-0910.google.com)
	by p02c11m115.mxlogic.net (mxl_mta-5.6.0-1)
	with ESMTP id c1ac6884.3326999472.3982.00-133.p02c11m115.mxlogic.net (envelope-from <miroslav.pokorny@gmail.com>);
	Wed, 23 Jul 2008 00:05:16 -0600 (MDT)
Received: by ti-out-0910.google.com with SMTP id w7so1165543tib.13
        for <mpokorny@atlassian.com>; Tue, 22 Jul 2008 23:05:15 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=gamma;
        h=domainkey-signature:received:received:message-id:date:from:to
         :subject:mime-version:content-type;
        bh=gM/hKrhvjVsG7aEiLgVAgBzydlKyM/ZOvyUyNUXnjTA=;
        b=Uq+6poNA8HfCucGQBzR1m0DQj8mw9o+go6j+Ucn/YS8Zh0Y4HmaEt8fv1TqaqeQ18N
         RZ1s1ObM+yif8zVpGsggUkpXaLkcunEsS1jwU5vR4g1YuEp+be2Dd7PmIAGOVL5WNwxj
         Ww+rRURFgi8Pi/IfcLHcrhbEugjJEdcu0xJ+Q=
DomainKey-Signature: a=rsa-sha1; c=nofws;
        d=gmail.com; s=gamma;
        h=message-id:date:from:to:subject:mime-version:content-type;
        b=pKETuU4eBujq4MMuoSNgpiJdgo+yo57AIlnQC1dKp6FTWpcmw9Hxhm5uqZFMv4wasN
         lYdz7ME36l5eDfIoTeCbKGsnuI921/AmMCiLjapUEwVEtbSicsS1O9n/2pyAMiAigLLp
         9cP3XRosF+75MZ0CWo0JlDDv1jNPB7bupkgTQ=
Received: by 10.110.37.3 with SMTP id k3mr5436179tik.29.1216793114915;
        Tue, 22 Jul 2008 23:05:14 -0700 (PDT)
Received: by 10.110.39.16 with HTTP; Tue, 22 Jul 2008 23:05:14 -0700 (PDT)
Message-ID: <3ba4a7240807222305v7d48eda0k1a172fc0b0aff679@mail.gmail.com>
Date: Wed, 23 Jul 2008 16:05:14 +1000
From: "Miroslav Pokorny" <miroslav.pokorny@gmail.com>
To: mpokorny@atlassian.com
Subject: GMailHtmlWithPlainTextAttachment
MIME-Version: 1.0
Content-Type: multipart/mixed; 
	boundary="----=_Part_141838_8425884.1216793114924"
X-Spam: [F=0.0138814853; B=0.500(0); spf=0.500; CM=0.500; MH=0.500(2008072232); R=0.112(108622192538); S=0.100(2008062001); SS=0.500; SC=none]
X-MAIL-FROM: <miroslav.pokorny@gmail.com>
X-SOURCE-IP: [209.85.142.191]
X-AnalysisOut: [v=1.0 c=1 a=Ags6qe5je1aH5tKPbUIA:9 a=NPbsqYj2Ee-j49JRezHW3]
X-AnalysisOut: [wKveI0A:4 a=yGn54wW5l98A:10 a=IhXo7UNJ67J5FJdSnBEA:9 a=wxh]
X-AnalysisOut: [uP7rlSv8zARVLOcVA1hpizhEA:4 a=qJMeZhlYfXQA:10 a=UkQVADylRH]
X-AnalysisOut: [oQDe35_-4A:9 a=B4ZL9Aceyyy4KNiHtBZYqplbhFwA:4 a=XF7b4UCPwd]
X-AnalysisOut: [8A:10]

------=_Part_141838_8425884.1216793114924
Content-Type: multipart/alternative; 
	boundary="----=_Part_141839_26284707.1216793114924"

------=_Part_141839_26284707.1216793114924
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: 7bit
Content-Disposition: inline

*BOLD*

*Italics*

-- 
mP

------=_Part_141839_26284707.1216793114924
Content-Type: text/html; charset=ISO-8859-1
Content-Transfer-Encoding: 7bit
Content-Disposition: inline

<div dir="ltr"><b>BOLD</b><br><br><i>Italics</i><br clear="all"><br>-- <br>mP
</div>

------=_Part_141839_26284707.1216793114924--

------=_Part_141838_8425884.1216793114924
Content-Type: text/plain; name=plain.txt
Content-Transfer-Encoding: base64
X-Attachment-Id: f_fizj6ult0
Content-Disposition: attachment; filename=plain.txt

VGhpcyBwbGFpbiB0ZXh0IGZpbGUgc2hvdWxkIGJlIGtlcHQuLi4=
------=_Part_141838_8425884.1216793114924--
