From jira-test@atlassian.com Fri Jun 20 12:15:38 2008
Return-Path: jira-test@atlassian.com
Received: from mail.atlassian.com (LHLO mail.atlassian.com) (63.246.22.40)
 by mail.atlassian.com with LMTP; Thu, 19 Jun 2008 21:15:36 -0500 (CDT)
Received: from squire (unknown [203.63.130.33])
	by mail.atlassian.com (Postfix) with ESMTP id 61CC816331B8
	for <mtokar@atlassian.com>; Thu, 19 Jun 2008 21:15:35 -0500 (CDT)
From: "Jira Test User" <jira-test@atlassian.com>
To: <mtokar@atlassian.com>
Subject: RE: This is a really long subject line in an effort to do bla bla bla bla bla bla bla yes long subject line it will go on and on until I elieve it is long enough
Date: Fri, 20 Jun 2008 12:14:21 +1000
MIME-Version: 1.0
Content-Type: multipart/mixed;
	boundary="----=_NextPart_000_000B_01C8D2CF.2C9A44B0"
X-Mailer: Microsoft Office Outlook, Build 11.0.5510
Thread-Index: AcjSexLyrcmCB9O0QeSUIOLb/TyepgAAEC4w
X-MimeOLE: Produced By Microsoft MimeOLE V6.00.2900.3028
Status: RO
Content-Length: 3898
Lines: 159

This is the body of the message.

------=_NextPart_000_000B_01C8D2CF.2C9A44B0
Content-Type: message/rfc822
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment

From: "Jira Test User" <jira-test@atlassian.com>
To: "'Jira Test User'" <jira-test@atlassian.com>
Subject: This is a really long subject line in an effort to do bla bla bla bla bla bla bla yes long subject line it will go on and on until I elieve it is long enough
Date: Fri, 20 Jun 2008 12:12:22 +1000
Message-ID: <20080620021336.55A4B16324DC@mail.atlassian.com>
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="----=_NextPart_000_0007_01C8D2CF.2C97FAC0"
X-Mailer: Microsoft Office Outlook, Build 11.0.5510
Thread-Index: AcjSexLyrcmCB9O0QeSUIOLb/Tyepg==
X-MimeOLE: Produced By Microsoft MimeOLE V6.00.2900.3028

This is a multi-part message in MIME format.

------=_NextPart_000_0007_01C8D2CF.2C97FAC0
Content-Type: text/plain;
	charset="us-ascii"
Content-Transfer-Encoding: 7bit

Testing this


------=_NextPart_000_0007_01C8D2CF.2C97FAC0
Content-Type: text/html;
	charset="us-ascii"
Content-Transfer-Encoding: quoted-printable

<html xmlns:o=3D"urn:schemas-microsoft-com:office:office" =
xmlns:w=3D"urn:schemas-microsoft-com:office:word" =
xmlns=3D"http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=3DContent-Type content=3D"text/html; =
charset=3Dus-ascii">
<meta name=3DGenerator content=3D"Microsoft Word 11 (filtered medium)">
<style>
<!--
 /* Style Definitions */
 p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	margin-bottom:.0001pt;
	font-size:12.0pt;
	font-family:"Times New Roman";}
a:link, span.MsoHyperlink
	{color:blue;
	text-decoration:underline;}
a:visited, span.MsoHyperlinkFollowed
	{color:purple;
	text-decoration:underline;}
span.EmailStyle17
	{mso-style-type:personal-compose;
	font-family:Arial;
	color:windowtext;}
@page Section1
	{size:595.3pt 841.9pt;
	margin:1.0in 1.25in 1.0in 1.25in;}
div.Section1
	{page:Section1;}
-->
</style>

</head>

<body lang=3DEN-GB link=3Dblue vlink=3Dpurple>

<div class=3DSection1>

<p class=3DMsoNormal><font size=3D2 face=3DArial><span =
style=3D'font-size:10.0pt;
font-family:Arial'>Testing this<o:p></o:p></span></font></p>

</div>

</body>

</html>

------=_NextPart_000_0007_01C8D2CF.2C97FAC0--

------=_NextPart_000_000B_01C8D2CF.2C9A44B0--
