Return-Path: jirauser@atlassian.com
Received: from mail.atlassian.com (LHLO mail.atlassian.com) (63.246.22.40)
 by mail.atlassian.com with LMTP; Thu, 10 Jul 2008 20:51:05 -0500 (CDT)
Received: from xpie7 (unknown [203.63.130.33])
	by mail.atlassian.com (Postfix) with ESMTP id EB8B516324F2
	for <jirauser@atlassian.com>; Thu, 10 Jul 2008 20:51:04 -0500 (CDT)
Message-ID: <001e01c8e2f9$514e9e20$9803a8c0@xpie7>
From: "jirauser" <jirauser@atlassian.com>
To: <jirauser@atlassian.com>
Content-class: urn:content-classes:message
MIME-Version: 1.0
Content-Type: multipart/related;
	type="multipart/alternative";
	boundary="=_reb-r4C46E9BF-t48DBBB27"
Subject: Outlook Rich Text With Inline Image
Date: Thu, 25 Sep 2008 10:23:58 -0600


--=_reb-r4C46E9BF-t48DBBB27
Content-Type: multipart/alternative;
	boundary="=_reb-r56AEF3F6-t48DBBB27"


--=_reb-r56AEF3F6-t48DBBB27
Content-Type: text/plain;
	charset=utf-8
Content-Transfer-Encoding: base64

anNwYQ0KLQ0KRm9yIG1vcmUgaW5mb3JtYXRpb24gb24gSklSQSwgc2VlOiBodHRwOi8vd3d3
LmF0bGFzc2lhbi5jb20vc29mdHdhcmUvamlyYQ0KDQogICAgICAgIA0K

--=_reb-r56AEF3F6-t48DBBB27
Content-Type: text/html;
	charset=utf-8
Content-Transfer-Encoding: base64

VCBGQUNFPSJDb25zb2xhcyI+Jm5ic3A7Jm5ic3A7Jm5ic3A7Jm5ic3A7Jm5ic3A7Jm5ic3A7
Jm5ic3A7IDwvRk9OVD48L1NQQU4+PC9QPg0KDQo8L0JPRFk+DQo8L0hUTUw+

--=_reb-r56AEF3F6-t48DBBB27--

--=_reb-r4C46E9BF-t48DBBB27
Content-Type: image/jpeg;
	name=image.jpeg
Content-Location: No%20AttachName
Content-Transfer-Encoding: base64

q6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6ur
q6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urqwAAAA==

--=_reb-r4C46E9BF-t48DBBB27--
