Return-Path: mpokorny@atlassian.com
Received: from mail.atlassian.com (LHLO mail.atlassian.com) (63.246.22.40)
 by mail.atlassian.com with LMTP; Wed, 23 Jul 2008 01:01:56 -0500 (CDT)
Received: from [192.168.3.151] (unknown [203.63.130.33])
	by mail.atlassian.com (Postfix) with ESMTP id 1DEDC3EAE56
	for <mpokorny@atlassian.com>; Wed, 23 Jul 2008 01:01:55 -0500 (CDT)
Message-ID: <4886C944.9070708@atlassian.com>
Date: Wed, 23 Jul 2008 16:01:40 +1000
From: Miroslav Pokorny <mpokorny@atlassian.com>
User-Agent: Thunderbird 2.0.0.14 (Windows/20080421)
MIME-Version: 1.0
To: mpokorny@atlassian.com
Subject: ThunderbirdHtmlWithPlainTextAttachment
Content-Type: multipart/mixed;
 boundary="------------060508000207070604050903"

This is a multi-part message in MIME format.
--------------060508000207070604050903
Content-Type: multipart/alternative;
 boundary="------------050303060702030703090408"


--------------050303060702030703090408
Content-Type: text/plain; charset=ISO-8859-1; format=flowed
Content-Transfer-Encoding: 7bit

Html

*Bold*

/Italics/

--------------050303060702030703090408
Content-Type: text/html; charset=ISO-8859-1
Content-Transfer-Encoding: 7bit

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
</head>
<body bgcolor="#ffffff" text="#000000">
Html<br>
<br>
<b>Bold</b><br>
<br>
<i>Italics</i><br>
</body>
</html>

--------------050303060702030703090408--

--------------060508000207070604050903
Content-Type: text/plain;
 name="plain.txt"
Content-Transfer-Encoding: base64
Content-Disposition: inline;
 filename="plain.txt"

VGhpcyBwbGFpbiB0ZXh0IGZpbGUgc2hvdWxkIGJlIGtlcHQuLi4=
--------------060508000207070604050903--
