/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.sysbliss.jira.plugins.workflow.model {

    [Bindable]
    [RemoteClass(alias="com.sysbliss.jira.plugins.workflow.model.FlexJiraResultImpl")]
    public class FlexJiraResultImpl extends FlexJiraResultImplBase implements FlexJiraResult {
        private static var serialVersionUID:Number= -1868641660471313801;
    }
}