/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.sysbliss.jira.plugins.workflow.model {

    [Bindable]
    [RemoteClass(alias="com.sysbliss.jira.plugins.workflow.model.FlexJiraActionImpl")]
    public class FlexJiraActionImpl extends FlexJiraActionImplBase implements FlexJiraAction {
        private static var serialVersionUID:Number= -5668812550634059964;
    }
}