package com.atlassian.jira.issue.thumbnail;

/**
 * The height and width of an image or thumbnail.
 * <p/>
 * This code was taken originally from our friends in Confluence
 *
 * @since v4.4
 */
public final class Dimensions
{
    private final int width;
    private final int height;

    public Dimensions(int width, int height)
    {
        this.height = height;
        this.width = width;
    }

    public int getWidth()
    {
        return width;
    }

    public int getHeight()
    {
        return height;
    }

    // generated by IDEA
    public boolean equals(Object o)
    {
        if (this == o) { return true; }
        if (o == null || getClass() != o.getClass()) { return false; }

        Dimensions that = (Dimensions) o;

        if (height != that.height) { return false; }
        if (width != that.width) { return false; }

        return true;
    }

    // generated by IDEA
    public int hashCode()
    {
        int result;
        result = width;
        result = 31 * result + height;
        return result;
    }

    public String toString()
    {
        return width + "x" + height;
    }
}
